config/routes.rb
require 'sidekiq/web'
require 'staff_constraint'

Rails.application.routes.draw do
  mount Peek::Railtie => '/peek'

  root to: 'pages#home'

  get  '/login',  to: 'sessions#new',     as: 'login'
  post '/logout', to: 'sessions#destroy', as: 'logout'

  match '/auth/:provider/callback', to: 'sessions#create',  via: [:get, :post]
  match '/auth/failure',            to: 'sessions#failure', via: [:get, :post]

  get '/autocomplete/github_repos', to: 'autocomplete#github_repos'

  resources :assignment_invitations, path: 'assignment-invitations', only: [:show] do
    member do
      patch :accept_invitation
      get   :successful_invitation, path: :success
    end
  end

  resources :group_assignment_invitations, path: 'group-assignment-invitations', only: [:show] do
    member do
      get   :accept
      patch :accept_assignment
      patch :accept_invitation
      get   :successful_invitation, path: :success
    end
  end

  scope path_names: { edit: 'settings' } do
    resources :organizations, path: 'classrooms' do
      member do
        get   :invite
        get   :new_assignment, path: 'new-assignment'
        get   :setup
        patch :setup_organization
        get   'settings/invitations', to: 'organizations#invitation'
        get   'settings/teams',       to: 'organizations#show_groupings'
      end

      resources :groupings, only: [:show, :edit, :update] do
        resources :groups, only: [:show] do
          member do
            patch '/memberships/:user_id', to: 'groups#add_membership', as: 'add_membership'
            delete '/memberships/:user_id', to: 'groups#remove_membership', as: 'remove_membership'
          end
        end
      end
      resources :assignments
      resources :group_assignments, path: 'group-assignments'
      resources :student_identifier_types, path: 'identifiers', except: [:show]
    end
  end

  namespace :stafftools do
    constraints StaffConstraint.new do
      mount Sidekiq::Web => '/sidekiq'
      mount Flipper::UI.app(GitHubClassroom.flipper) => '/flipper', as: 'flipper'
    end

    root 'resources#index', as: :root
    get '/resource_search', to: 'resources#search'

    resources :users, only: [:show] do
      member do
        post :impersonate
        delete :stop_impersonating
      end
    end

    resources :organizations, path: 'classrooms', only: [:show]

    resources :repo_accesses, only: [:show]

    resources :assignment_invitations, only: [:show]
    resources :assignment_repos,       only: [:show]
    resources :assignments,            only: [:show]

    resources :group_assignment_invitations, path: 'group-assignment-invitations', only: [:show]
    resources :group_assignment_repos,       path: 'group-assignment-repos',       only: [:show]
    resources :group_assignments,            path: 'group-assignments',            only: [:show]

    resources :groupings, only: [:show]
    resources :groups,    only: [:show]
  end
end

app/controllers/student_identifier_types_controller.rb
# frozen_string_literal: true
class StudentIdentifierTypesController < ApplicationController
  include OrganizationAuthorization

  before_action :ensure_student_identifier_flipper_is_enabled
  before_action :set_student_identifier_type, only: [:edit, :update]
  before_action :save_referer,                only: [:new]

  def index
    @student_identifier_types = @organization.student_identifier_types
  end

  def new
    @student_identifier_type = StudentIdentifierType.new
  end

  def edit
  end

  def create
    @student_identifier_type = StudentIdentifierType.new(student_identifier_type_params)
    if @student_identifier_type.save
      flash[:success] = "\"#{student_identifier_type.name}\" has been created!"
      redirect_to session.delete(:return_to) || { action: 'index' }
    else
      render :new
    end
  end

  def update
    @student_identifier_type.update_attributes(student_identifier_type_params)
    if @student_identifier_type.save
      flash[:success] = "\"#{student_identifier_type.name}\" has been updated!"
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  def destroy
    student_identifier_type = StudentIdentifierType.find_by(id: params[:id])
    if student_identifier_type.update_attributes(deleted_at: Time.zone.now)
      DestroyResourceJob.perform_later(student_identifier_type)
      flash[:success] = "\"#{student_identifier_type.name}\" is being deleted"
    end
    redirect_to action: 'index'
  end

  def student_identifier_type_params
    params
      .require(:student_identifier_type)
      .permit(:name, :description, :content_type)
      .merge(organization: @organization)
  end

  private

  def set_student_identifier_type
    @student_identifier_type = StudentIdentifierType.find_by(id: params[:id])
  end

  def save_referer
    session[:return_to] = request.referer
  end

  def student_identifier_type
    @student_identifier_type ||= StudentIdentifierType.find_by(id: params[:id])
  end
  helper_method :student_identifier_type
end

app/views/student_identifier_types/_form_options.html.erb
<dl class="form">
  <dt><%= f.label :name %></dt>
  <dd><%= f.text_field :name, class: 'textfield' %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :description %></dt>
  <dd><%= f.text_field :description, class: 'textfield' %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :content_type %></dt>
  <dd><%= f.select :content_type, StudentIdentifierType.content_types.map { |key, value| [key.humanize, key] } %></dd>
</dl>

app/views/student_identifier_types/_student_identifier_type.html.erb
<div class="identifier-type-list-item flex-table">
  <div class="flex-table-item">
    <strong><%= student_identifier_type.name %></strong>
    <p class="identifier-type-description text-muted"><%= student_identifier_type.description %></p>
  </div>

  <div class="btn-group right">
    <%= link_to 'Edit', edit_organization_student_identifier_type_path(@organization, student_identifier_type), class: 'btn', role: 'button' %>
    <%= link_to 'Delete', '#', class: 'btn btn-danger', 'data-remodal-target': "delete-identifier-type-#{student_identifier_type.id}" %>
  </div>

  <small class="meta-data right"><%= pluralize(student_identifier_type.student_identifiers.count , 'student') %></small>

</div>

<div class="remodal text-left" data-remodal-id="<%= "delete-identifier-type-#{student_identifier_type.id}" %>">
  <button data-remodal-action="close" class="remodal-close"><%= octicon('x') %></button>
  <h2 class="remodal-header">Are you sure you want to delete this identifier type?</h2>

  <div class="remodal-warning">
    Any assignments or group assignments using this identifier type will no longer ask for student identification. All recorded student identifiers of this type will be removed. You cannot undo this action.
  </div>

  <%= form_for [@organization, student_identifier_type], html: { method: 'delete' } do |f| %>
      <%= f.submit 'I understand, delete this identifier', class: 'btn btn-danger btn-block js-navigation js-submit' %>
  <% end %>
</div>

app/views/student_identifier_types/edit.html.erb
<%= render 'organizations/organization_banner' %>

<div class="site-content">
  <div class="site-content-cap">
    <h2 class="site-content-heading">Edit identifier type</h2>
  </div>
</div>

<div class="site-content-body">
  <div class="flash flash-with-icon flash-form">
    <%= octicon 'alert' %>
    Please do not ask students to provide any confidential information (e.g. SSN or bank account number) as their identifiers.
  </div>
  <%= form_for [@organization, @student_identifier_type] do |f| %>
      <%= render partial: 'student_identifier_types/form_options', locals: { f: f } %>
      <div class="form-actions">
        <%= f.submit 'Save changes', class: 'btn btn-green js-navigation' %>
        <%= link_to 'Cancel', organization_student_identifier_types_path(@organization), class: 'btn', role: 'button'%>
      </div>
  <% end %>
</div>

app/views/student_identifier_types/index.html.erb
<div class="remodal-bg">
  <%= render 'organizations/organization_banner' %>
  <div class="columns">
    <div class="one-fourth column">
      <%= render partial: 'organizations/side_menu' %>
    </div>
    <div class="three-fourths column">
      <div class="boxed-group">
        <% if @student_identifier_types.present? %>
            <%= link_to 'New identifier type', new_organization_student_identifier_type_path(@organization), class: 'btn btn-sm boxed-group-action', role: 'button'%>
        <% end %>
        <h3>Student identifier types</h3>
        <div class="boxed-group-inner clearfix">
          <% if @student_identifier_types.present? %>
              <div class="identifier-type-list-items">
                <%= render @student_identifier_types %>
              </div>
          <% else %>
              <div class="blankslate large-format spacious clean-background">
                <h3>This organization doesn't have any student identifier types yet.</h3>
                <%= link_to new_organization_student_identifier_type_path(@organization), class: 'btn btn-green btn-big', role: 'button' do %>
                    Create your first student identifier type
                <% end %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/student_identifier_types/new.html.erb
<%= render 'organizations/organization_banner' %>

<div class="site-content">
  <div class="site-content-cap">
    <h2 class="site-content-heading">
      New identifier type
    </h2>
  </div>
</div>

<div class="site-content-body">
  <div class="flash flash-with-icon flash-form">
    <%= octicon 'alert' %>
    Please do not ask students to provide any confidential information (e.g. SSN or bank account number) as their identifiers.
  </div>
  <%= form_for [@organization, @student_identifier_type] do |f| %>
      <%= render partial: 'student_identifier_types/form_options', locals: { f: f } %>
      <div class="form-actions">
        <%= f.submit 'Create Identifier', class: 'btn btn-green js-navigation' %>
        <%= link_to 'Cancel', session[:return_to], class: 'btn', role: 'button'%>
      </div>
  <% end %>
</div>