config/routes.rb
require 'sidekiq/web'
require 'staff_constraint'

Rails.application.routes.draw do
  mount Peek::Railtie => '/peek'

  root to: 'pages#home'

  get  '/login',  to: 'sessions#new',     as: 'login'
  post '/logout', to: 'sessions#destroy', as: 'logout'

  match '/auth/:provider/callback', to: 'sessions#create',  via: [:get, :post]
  match '/auth/failure',            to: 'sessions#failure', via: [:get, :post]

  get '/autocomplete/github_repos', to: 'autocomplete#github_repos'

  resources :assignment_invitations, path: 'assignment-invitations', only: [:show] do
    member do
      patch :accept_invitation
      get   :successful_invitation, path: :success
    end
  end

  resources :group_assignment_invitations, path: 'group-assignment-invitations', only: [:show] do
    member do
      get   :accept
      patch :accept_assignment
      patch :accept_invitation
      get   :successful_invitation, path: :success
    end
  end

  scope path_names: { edit: 'settings' } do
    resources :organizations, path: 'classrooms' do
      member do
        get   :invite
        get   :new_assignment, path: 'new-assignment'
        get   :setup
        patch :setup_organization
        get   'settings/invitations', to: 'organizations#invitation'
        get   'settings/teams',       to: 'organizations#show_groupings'
      end

      resources :groupings, only: [:show, :edit, :update] do
        resources :groups, only: [:show] do
          member do
            patch '/memberships/:user_id', to: 'groups#add_membership', as: 'add_membership'
            delete '/memberships/:user_id', to: 'groups#remove_membership', as: 'remove_membership'
          end
        end
      end
      resources :assignments
      resources :group_assignments, path: 'group-assignments'
      resources :student_identifier_types, path: 'identifiers', except: [:show]
    end
  end

  namespace :stafftools do
    constraints StaffConstraint.new do
      mount Sidekiq::Web => '/sidekiq'
      mount Flipper::UI.app(GitHubClassroom.flipper) => '/flipper', as: 'flipper'
    end

    root 'resources#index', as: :root
    get '/resource_search', to: 'resources#search'

    resources :users, only: [:show] do
      member do
        post :impersonate
        delete :stop_impersonating
      end
    end

    resources :organizations, path: 'classrooms', only: [:show]

    resources :repo_accesses, only: [:show]

    resources :assignment_invitations, only: [:show]
    resources :assignment_repos,       only: [:show]
    resources :assignments,            only: [:show]

    resources :group_assignment_invitations, path: 'group-assignment-invitations', only: [:show]
    resources :group_assignment_repos,       path: 'group-assignment-repos',       only: [:show]
    resources :group_assignments,            path: 'group-assignments',            only: [:show]

    resources :groupings, only: [:show]
    resources :groups,    only: [:show]
  end
end

app/views/shared/_assignment_student_identifier_type_options.html.erb
<% if student_identifier_enabled? %>
  <dl class="form">
    <dt><label>Use a student identifier type</label></dt>

    <% if student_identifier_types.present? %>
        <dl class="form">
          <%= select(:student_identifier_type, :id, options_for_select(student_identifier_types, selected = assignment.student_identifier_type.present? ? assignment.student_identifier_type.id : nil), include_blank: true ) %>
          <p class="note">
            Students will be required to enter their identifiers before accepting the assignment.
          </p>
        </dl>
    <% else %>
        <%= link_to new_organization_student_identifier_type_path(@organization), class: 'btn btn-green js-navigation' do %>
            Create your first student identifier
        <% end %>
        <p class="note">
          Students will be required to enter their identifiers before accepting the assignment.
        </p>
    <% end %>
  </dl>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="flash-form">
    <div class="flash flash-error">
      <span class="flash-close js-flash-close">
        <%= octicon('x') %>
      </span>
      <% if object.errors.count > 1 %>
        <% object.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      <% else %>
        <% object.errors.full_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="flash-application container">
    <%= content_tag :div, class: "flash #{primer_class_for(type)}" do %>
      <span class="flash-close js-flash-close">
        <%= octicon('x') %>
      </span>
      <%= message %>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="site-footer text-center">
  <div class="container">
    <div class="made-with-heart">
      <%= octicon 'mortar-board' %> with <%= octicon 'heart' %> by <%= link_to octicon('logo-github'), 'https://education.github.com' %>
    </div>
  </div>
  GitHub Classroom is <%= link_to 'open source', 'https://github.com/education/classroom' %>.
</footer>

app/views/shared/_header.html.erb
<header class="site-header">
  <div class="container">
    <%= link_to(image_tag('logo@2x.png', class: 'site-logo', alt: 'GitHub for Classrooms'), (logged_in? ? organizations_path : root_path)) %>

    <nav class="site-nav">
      <ul>
        <li>
          <%= link_to "GitHub Education", 'https://education.github.com', target: '_blank' %>
        </li>

        <% if logged_in? %>
          <li>
            <%= link_to 'https://education.github.com/forum', class: 'tooltipped tooltipped-s', 'aria-label' => 'Community discussion' do %>
              <%= octicon 'comment-discussion' %>
            <% end %>
          </li>

          <li>
            <%= link_to 'https://github.com/education/classroom/issues/new?labels[]=report', class: 'tooltipped tooltipped-s', 'aria-label' => 'Report a bug' do %>
              <%= octicon 'bug' %>
            <% end %>
          </li>

          <li>
            <% if impersonating?(current_user, true_user) %>
              <%= link_to stop_impersonating_stafftools_user_path(current_user), class: 'tooltipped tooltipped-s', method: :delete, 'aria-label' => "Stop impersonating @#{current_user.github_user.login}" do %>
                <div class="avatar-parent-child left">
                  <%= image_tag current_user.github_user.github_avatar_url(40), class: 'avatar', alt: "@#{current_user.github_user.login}", height: 20, width: 20 %>
                  <%= image_tag true_user.github_user.github_avatar_url(20), class: 'avatar avatar-child', alt: "@#{true_user.github_user.login}", height: 10, width: 10 %>
                </div>
              <% end %>
            <% else %>
              <%= link_to current_user.github_user.html_url, class: 'tooltipped tooltipped-s', 'aria-label' => 'View GitHub profile' do %>
                <%= image_tag current_user.github_user.github_avatar_url(40), class: 'avatar', alt: "@#{current_user.github_user.login}", height: 20, width: 20 %>
              <% end %>
            <% end %>
          </li>

          <li>
            <%= link_to logout_path, method: :post, class: 'tooltipped tooltipped-s', 'aria-label' => 'Sign out' do %>
              <%= octicon 'sign-out' %>
            <% end %>
          </li>

        <% else %>
          <li><%= link_to 'Sign in', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

<% if controller_path.split('/').first == 'stafftools' %>
  <div class="stafftools-border"></div>
<% end %>

app/views/shared/_invitation.html.erb
<form>
  <% if mobile? %>
    <%= render partial: "shared/invitations/mobile", locals: local_assigns %>
  <% else %>
    <%# if for some reason the user has a really tiny desktop screen fallback to the mobile view" %>
    <%= render partial: "shared/invitations/mobile", locals: local_assigns %>
    <%= render partial: "shared/invitations/desktop", locals: local_assigns %>
  <% end %>
</form>

app/views/shared/_invitation_header.html.erb
<header class="site-header">
  <div class="container">
    <%= image_tag('logo@2x.png', :class => 'site-logo', :alt => 'GitHub for Classrooms') %>

    <nav class="site-nav">
      <ul>
        <li>
          <%= link_to "GitHub Education", 'https://education.github.com', target: '_blank' %>
        </li>

        <li>
          <%= link_to 'https://education.github.com/forum', class: 'tooltipped tooltipped-s', 'aria-label' => 'Community discussion' do %>
            <%= octicon 'comment-discussion' %>
          <% end %>
        </li>

        <li>
          <%= link_to 'https://github.com/education/classroom/issues/new', class: 'tooltipped tooltipped-s', 'aria-label' => 'Report a bug' do %>
            <%= octicon 'bug' %>
          <% end %>
        </li>

        <li>
          <%= link_to current_user.github_user.html_url, class: 'tooltipped tooltipped-s', 'aria-label' => 'View GitHub profile' do %>
            <%= image_tag current_user.github_user.github_avatar_url(40), class: 'avatar', alt: "@#{current_user.github_user.login}", height: 20, width: 20 %>
          <% end %>
        </li>

        <li>
          <%= link_to logout_path, method: :post, class: 'tooltipped tooltipped-s', 'aria-label' => 'Sign out' do %>
            <%= octicon 'sign-out' %>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_message_of_the_day.html.erb
<% if ENV['MOTD'].present? %>
  <div class="message-of-the-day">
    <div class="container">
      <p><%= ENV['MOTD'].html_safe %></p>
    </div>
  </div>
<% end %>

app/views/shared/_open_graph.html.erb
<meta property="og:title" content="GitHub Classroom" />
<meta property="og:type" content="website" />
<meta property="og:description" content="GitHub Classroom automates repository creation and access control, making it easy for teachers to distribute starter code and collect assignments on GitHub." />
<meta property="og:url" content="https://classroom.github.com/" />
<meta property="og:image" content="https://classroom.github.com/images/og-image.png" />

app/views/shared/_pagination.html.erb
<% if collection.next_page || collection.prev_page %>
  <div class="paginate-container container">
    <%= paginate collection %>
  </div>
<% end %>