config/routes.rb
require 'sidekiq/web'
require 'staff_constraint'

Rails.application.routes.draw do
  mount Peek::Railtie => '/peek'

  root to: 'pages#home'

  get  '/login',  to: 'sessions#new',     as: 'login'
  post '/logout', to: 'sessions#destroy', as: 'logout'

  match '/auth/:provider/callback', to: 'sessions#create',  via: [:get, :post]
  match '/auth/failure',            to: 'sessions#failure', via: [:get, :post]

  get '/autocomplete/github_repos', to: 'autocomplete#github_repos'

  resources :assignment_invitations, path: 'assignment-invitations', only: [:show] do
    member do
      patch :accept_invitation
      get   :successful_invitation, path: :success
    end
  end

  resources :group_assignment_invitations, path: 'group-assignment-invitations', only: [:show] do
    member do
      get   :accept
      patch :accept_assignment
      patch :accept_invitation
      get   :successful_invitation, path: :success
    end
  end

  scope path_names: { edit: 'settings' } do
    resources :organizations, path: 'classrooms' do
      member do
        get   :invite
        get   :new_assignment, path: 'new-assignment'
        get   :setup
        patch :setup_organization
        get   'settings/invitations', to: 'organizations#invitation'
        get   'settings/teams',       to: 'organizations#show_groupings'
      end

      resources :groupings, only: [:show, :edit, :update] do
        resources :groups, only: [:show] do
          member do
            patch '/memberships/:user_id', to: 'groups#add_membership', as: 'add_membership'
            delete '/memberships/:user_id', to: 'groups#remove_membership', as: 'remove_membership'
          end
        end
      end
      resources :assignments
      resources :group_assignments, path: 'group-assignments'
      resources :student_identifier_types, path: 'identifiers', except: [:show]
    end
  end

  namespace :stafftools do
    constraints StaffConstraint.new do
      mount Sidekiq::Web => '/sidekiq'
      mount Flipper::UI.app(GitHubClassroom.flipper) => '/flipper', as: 'flipper'
    end

    root 'resources#index', as: :root
    get '/resource_search', to: 'resources#search'

    resources :users, only: [:show] do
      member do
        post :impersonate
        delete :stop_impersonating
      end
    end

    resources :organizations, path: 'classrooms', only: [:show]

    resources :repo_accesses, only: [:show]

    resources :assignment_invitations, only: [:show]
    resources :assignment_repos,       only: [:show]
    resources :assignments,            only: [:show]

    resources :group_assignment_invitations, path: 'group-assignment-invitations', only: [:show]
    resources :group_assignment_repos,       path: 'group-assignment-repos',       only: [:show]
    resources :group_assignments,            path: 'group-assignments',            only: [:show]

    resources :groupings, only: [:show]
    resources :groups,    only: [:show]
  end
end

app/models/organization.rb
# frozen_string_literal: true
class Organization < ApplicationRecord
  include Flippable
  include Sluggable

  update_index('stafftools#organization') { self }

  default_scope { where(deleted_at: nil) }

  has_many :assignments,              dependent: :destroy
  has_many :groupings,                dependent: :destroy
  has_many :group_assignments,        dependent: :destroy
  has_many :repo_accesses,            dependent: :destroy
  has_many :student_identifier_types, dependent: :destroy

  has_and_belongs_to_many :users

  validates :github_id, presence: true, uniqueness: true

  validates :title, presence: true
  validates :title, length: { maximum: 60 }

  validates :slug, uniqueness: true

  validates :webhook_id, uniqueness: true, allow_nil: true

  before_destroy :silently_remove_organization_webhook

  def all_assignments(with_invitations: false)
    return assignments + group_assignments unless with_invitations

    assignments.includes(:assignment_invitation) + \
      group_assignments.includes(:group_assignment_invitation)
  end

  def github_client
    token = users.limit(1).order('RANDOM()').pluck(:token)[0]
    Octokit::Client.new(access_token: token)
  end

  def github_organization
    @github_organization ||= GitHubOrganization.new(github_client, github_id)
  end

  def slugify
    self.slug = "#{github_id} #{title}".parameterize
  end

  def create_organization_webhook(webhook_url)
    webhook = github_organization.create_organization_webhook(config: { url: webhook_url })
    update_attributes(webhook_id: webhook.id)
  end

  def silently_remove_organization_webhook
    github_organization.remove_organization_webhook(webhook_id)
    true
  end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true
class OrganizationsController < ApplicationController
  include OrganizationAuthorization

  before_action :ensure_team_management_flipper_is_enabled, only: [:show_groupings]

  before_action :authorize_organization_addition,     only: [:create]
  before_action :set_users_github_organizations,      only: [:index, :new, :create]
  before_action :add_current_user_to_organizations,   only: [:index]
  before_action :paginate_users_github_organizations, only: [:new, :create]

  skip_before_action :set_organization, :authorize_organization_access, only: [:index, :new, :create]

  def index
    @organizations = current_user.organizations.includes(:users).page(params[:page])
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(new_organization_params)

    if @organization.save
      redirect_to setup_organization_path(@organization)
    else
      render :new
    end
  end

  def show
    @assignments = Kaminari
                   .paginate_array(@organization.all_assignments(with_invitations: true)
                   .sort_by(&:updated_at))
                   .page(params[:page])
  end

  def edit
  end

  def invitation
  end

  def show_groupings
    @groupings = @organization.groupings
  end

  def update
    if @organization.update_attributes(update_organization_params)
      flash[:success] = "Organization \"#{@organization.title}\" updated"
      redirect_to @organization
    else
      render :edit
    end
  end

  def destroy
    if @organization.update_attributes(deleted_at: Time.zone.now)
      DestroyResourceJob.perform_later(@organization)

      flash[:success] = "Your organization, @#{@organization.github_organization.login} is being reset"
      redirect_to organizations_path
    else
      render :edit
    end
  end

  def new_assignment
  end

  def invite
  end

  def setup
  end

  def setup_organization
    if @organization.update_attributes(update_organization_params)
      redirect_to invite_organization_path(@organization)
    else
      render :setup
    end
  end

  private

  def authorize_organization_addition
    new_github_organization = github_organization_from_params

    return if new_github_organization.admin?(current_user.github_user.login)
    raise NotAuthorized, 'You are not permitted to add this organization as a classroom'
  end

  def github_organization_from_params
    @github_organization_from_params ||= GitHubOrganization.new(current_user.github_client,
                                                                params[:organization][:github_id].to_i)
  end

  def new_organization_params
    github_org = github_organization_from_params
    title      = github_org.name.present? ? github_org.name : github_org.login

    params
      .require(:organization)
      .permit(:github_id)
      .merge(users: [current_user])
      .merge(title: title)
  end

  def set_organization
    @organization = Organization.find_by!(slug: params[:id])
  end

  def set_users_github_organizations
    @users_github_organizations = current_user.github_user.organization_memberships.map do |membership|
      {
        classroom: Organization.unscoped.includes(:users).find_by(github_id: membership.organization.id),
        github_id: membership.organization.id,
        login:     membership.organization.login,
        role:      membership.role
      }
    end
  end

  # Check if the current user has any organizations with admin privilege,
  # if so add the user to the corresponding classroom automatically.
  def add_current_user_to_organizations
    @users_github_organizations.each do |organization|
      classroom = organization[:classroom]
      if classroom.present? && !classroom.users.include?(current_user)
        create_user_organization_access(classroom)
      end
    end
  end

  def create_user_organization_access(organization)
    github_org = GitHubOrganization.new(current_user.github_client, organization.github_id)
    return unless github_org.admin?(current_user.github_user.login)
    organization.users << current_user
  end

  def paginate_users_github_organizations
    @users_github_organizations = Kaminari.paginate_array(@users_github_organizations).page(params[:page]).per(24)
  end

  def update_organization_params
    params
      .require(:organization)
      .permit(:title)
  end
end

app/controllers/stafftools/assignment_invitations_controller.rb
# frozen_string_literal: true
module Stafftools
  class AssignmentInvitationsController < StafftoolsController
    before_action :set_assignment_invitation

    def show
    end

    private

    def set_assignment_invitation
      @assignment_invitation = AssignmentInvitation.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/assignment_repos_controller.rb
# frozen_string_literal: true
module Stafftools
  class AssignmentReposController < StafftoolsController
    before_action :set_assignment_repo

    def show
    end

    private

    def set_assignment_repo
      @assignment_repo = AssignmentRepo.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/assignments_controller.rb
# frozen_string_literal: true
module Stafftools
  class AssignmentsController < StafftoolsController
    before_action :set_assignment

    def show
    end

    private

    def set_assignment
      @assignment = Assignment.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/group_assignment_invitations_controller.rb
# frozen_string_literal: true
module Stafftools
  class GroupAssignmentInvitationsController < StafftoolsController
    before_action :set_group_assignment_invitation

    def show
    end

    private

    def set_group_assignment_invitation
      @group_assignment_invitation = GroupAssignmentInvitation.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/group_assignment_repos_controller.rb
# frozen_string_literal: true
module Stafftools
  class GroupAssignmentReposController < StafftoolsController
    before_action :set_group_assignment_repo

    def show
    end

    private

    def set_group_assignment_repo
      @group_assignment_repo = GroupAssignmentRepo.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/group_assignments_controller.rb
# frozen_string_literal: true
module Stafftools
  class GroupAssignmentsController < StafftoolsController
    before_action :set_group_assignment

    def show
    end

    private

    def set_group_assignment
      @group_assignment = GroupAssignment.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/groupings_controller.rb
# frozen_string_literal: true
module Stafftools
  class GroupingsController < StafftoolsController
    before_action :set_grouping

    def show
    end

    private

    def set_grouping
      @grouping = Grouping.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/groups_controller.rb
# frozen_string_literal: true
module Stafftools
  class GroupsController < StafftoolsController
    before_action :set_group

    def show
    end

    private

    def set_group
      @group = Group.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/organizations_controller.rb
# frozen_string_literal: true
module Stafftools
  class OrganizationsController < StafftoolsController
    before_action :set_organization

    def show
    end

    private

    def set_organization
      @organization = Organization.includes(:users).find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/repo_accesses_controller.rb
# frozen_string_literal: true
module Stafftools
  class RepoAccessesController < StafftoolsController
    before_action :set_repo_access

    def show
    end

    private

    def set_repo_access
      @repo_access = RepoAccess.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/resources_controller.rb
# frozen_string_literal: true
module Stafftools
  class ResourcesController < StafftoolsController
    before_action :set_resources

    def index
    end

    def search
      respond_to do |format|
        format.html { render partial: 'stafftools/resources/search_results', locals: { resources: @resources } }
      end
    end

    private

    def set_resources
      return @resources = nil unless params[:query].present?
      @resources = StafftoolsIndex
                   .query(match_phrase_prefix(params[:query]))
                   .order(_type: :asc)
                   .page(params[:page])
                   .per(20)
    end

    def match_phrase_prefix(query)
      searchable_fields = %w(github_id github_repo_id github_team_id id key login name slug title uid)
      { bool: { should: searchable_fields.map { |field| { 'match_phrase_prefix' => { field => query } } } } }
    end
  end
end

app/controllers/stafftools/users_controller.rb
# frozen_string_literal: true
module Stafftools
  class UsersController < StafftoolsController
    skip_before_action :authorize_access, only: [:stop_impersonating]

    before_action :set_user, except: [:stop_impersonating]

    def show
    end

    def impersonate
      session[:impersonated_user_id] = @user.id
      redirect_to root_path
    end

    def stop_impersonating
      not_found unless true_user.try(:staff?)

      session.delete(:impersonated_user_id)
      redirect_to stafftools_root_path
    end

    private

    def set_user
      @user = User.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools_controller.rb
# frozen_string_literal: true
class StafftoolsController < ApplicationController
  layout 'stafftools'

  before_action :authorize_access

  private

  def authorize_access
    not_found unless current_user.try(:staff?)
  end
end

app/views/stafftools/organizations/_assignment.html.erb
<li class="clearfix">
  <%= octicon 'person' %>
  <strong><%= link_to assignment.title, stafftools_assignment_path(assignment.id) %></strong>
</li>

app/views/stafftools/organizations/_group_assignment.html.erb
<li class="clearfix">
  <%= octicon 'organization' %>
  <strong><%= link_to group_assignment.title, stafftools_group_assignment_path(group_assignment.id) %></strong>
</li>

app/views/stafftools/organizations/_grouping.html.erb
<li class="clearfix">
  <%= octicon 'organization' %>
  <strong><%= link_to grouping.title, stafftools_grouping_path(grouping.id) %></strong>
</li>

app/views/stafftools/organizations/_organization.html.erb
<div class="classroom-resource-item">
  <%= image_tag github_avatar_url(organization.github_id, 96), height: 48, width: 48, class: 'avatar left', alt: "@#{organization.login}" %>

  <%= link_to stafftools_organization_path(organization.id) do %>
    <strong class="search-result-title"><%= organization.login %></strong>
  <% end %>

  <span class="text-muted css-truncate css-truncate-target">Added <%= local_time_ago(organization.created_at) %></span><br>
</div>

app/views/stafftools/organizations/_user.html.erb
<li class="clearfix">
  <%= image_tag user.github_user.github_avatar_url(40), height: 20, width: 20, alt: "@#{user.github_user.login}" %>
  <strong><%= link_to user.github_user.login, stafftools_user_path(user.id) %></strong>
</li>

app/views/stafftools/organizations/show.html.erb
<div class="site-content">
  <div class="stafftools-page-header clearfix">
    <span class="assignment-icon assignment-icon-individual left">
      <%= image_tag @organization.github_organization.github_avatar_url(96), height: 48, width: 48, class: 'avatar left', alt: "@#{@organization.github_organization.login}" %>
    </span>

    <h2 class="stafftools-heading">
      <%= @organization.title %>
    </h2>

    <p class="assignment-type text-muted">Classroom</p>
  </div>

  <div class="boxed-group">
    <h3>Classroom information</h3>

    <div class="boxed-group-inner">
      <table>
        <tr>
          <td class="text-emphasized">ID</td>
          <td><%= @organization.id %></td>
        </tr>
        <tr>
          <td class="text-emphasized">GitHub ID</td>
          <td><%= @organization.github_id %></td>
        </tr>
        <tr>
          <td class="text-emphasized">Classroom</td>
          <td><%= link_to organization_url(@organization), organization_url(@organization) %></td>
        </tr>
        <tr>
          <td class="text-emphasized">GitHub</td>
          <td><%= link_to @organization.github_organization.html_url, @organization.github_organization.html_url %></td>
        </tr>
        <tr>
          <td class="text-emphasized">Joined on</td>
          <td><%= local_time(@organization.created_at) %></td>
        </tr>
        <tr>
          <td class="text-emphasized">Last updated</td>
          <td><%= local_time(@organization.updated_at) %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="boxed-group">
    <h3>Owners</h3>

    <div class="boxed-group-inner">
      <ul class="boxed-group-list standalone">
        <%= render partial: 'stafftools/organizations/user', collection: @organization.users %>
      </ul>
    </div>
  </div>

  <% if @organization.all_assignments.present? %>
    <div class="boxed-group">
      <h3>Assignments</h3>

      <div class="boxed-group-inner">
        <ul class="boxed-group-list standalone">
          <% @organization.all_assignments.each do |assignment| %>
            <% type = assignment.class.to_s.underscore %>
            <%= render partial: "stafftools/organizations/#{type}", locals: { :"#{type}" => assignment } %>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <% if @organization.groupings.present? %>
    <div class="boxed-group">
      <h3>Groupings</h3>

      <div class="boxed-group-inner">
        <ul class="boxed-group-list standalone">
          <%= render partial: "stafftools/organizations/grouping", collection: @organization.groupings %>
        </ul>
      </div>
    </div>
  <% end %>
</div>